---
- name: Setup Banking DevSecOps Application
  hosts: banking_servers
  vars:
    project_path: "{{ lookup('env', 'BANKING_PROJECT_PATH') | default(playbook_dir + '/..') }}"

  roles:
    - docker
    - banking-app
